[package]
name = "cli-news"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
colour = "0.6.0"
newsapi = {path = "./newsapi/"}
